- hosts: pvenodes
  tasks:

    # note: this might fail if the enterprise repositories are still mapped.
    # maybe add a task that replaces the enterprise repositories with the non-paid ones here.
    - name: install sudo package
      apt:
        name: sudo
        update_cache: yes
        cache_valid_time: 3600
        state: latest

    - name: create Ansible user
      user:
        name: ansible
        shell: '/bin/bash'

    - name: add Ansible ssh key
      authorized_key:
        user: ansible
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_ecdsa.pub') }}"

    - name: Check if sudoer file exists
      stat:
        path: "/etc/sudoers.d/ansible"
      register: result

    - name: add ansible to sudoers
      # this task _will_ fail if we try to copy a file again (since it's 0440 chmoded), so we skip it
      # if we already ran it
      when: not result.stat.exists
      copy:
        src: sudoer_ansible
        dest: /etc/sudoers.d/ansible
        owner: root
        group: root
        mode: 0440