- hosts: uptimekuma
  gather_facts: false

  roles:
    - update_cts
    - install_docker_debian
    - role: install_nginx
      courgettes_subdomain: "uptime"
    - role: install_uptimekuma_cts
      courgettes_subdomain: "uptime"
