- hosts: vpn
  gather_facts: false

  roles:
    - role: update_cts
    - install_tailscale_exit_node

- hosts: localhost
  gather_facts: false
  tasks:
    - name: Updates to perform on tailscale side
      ansible.builtin.debug:
        msg: >
          Accept router and exit node in tailscale webapp.
          Disable key expiry of new node.

- hosts: jumphost
  gather_facts: false

  roles:
    - role: update_cts
      fail2ban_allow_ips: [ "172.16.0.0/12" ]
    - install_docker_debian
    - install_jumphost_cts
    - role: install_rathole
      rathole_mode: client
