- hosts: vpn
  gather_facts: false

  roles:
    - role: update_cts
    - role: install_tailscale_exit_node
      routes_flag: "--advertise-routes=10.10.0.0/24,10.10.1.0/24,10.10.2.0/24,10.10.3.0/24,10.10.4.0/24,10.10.5.0/24"

- hosts: localhost
  gather_facts: false
  tasks:
    - name: Updates to perform on tailscale side
      ansible.builtin.debug:
        msg: >
          Accept router and exit node in tailscale webapp.
          Disable key expiry of new node.

- hosts: jumphost
  gather_facts: false

  roles:
    - role: update_cts
      fail2ban_allow_ips: [ "172.16.0.0/12" ]
    - install_docker_debian
    - install_jumphost_cts
    #- role: install_rathole
    #  rathole_mode: client
