[client]
default_token = "{{rathole_token}}"
remote_addr = "vps.courgettes.club:2333"

[client.services.ssh]
local_addr = "host.docker.internal:22"

[client.services.http]
local_addr = "10.10.5.250:80"

[client.services.https]
local_addr = "10.10.5.250:443"

[server]
default_token = "{{rathole_token}}"
bind_addr = "0.0.0.0:2333"

# Important: ports should be open in docker-compose as well as in VPS firewall rules
[server.services.ssh]
bind_addr = "0.0.0.0:22"

[server.services.http]
bind_addr = "0.0.0.0:80"

[server.services.https]
bind_addr = "0.0.0.0:443"

