version: '3.1'
services:
  rathole:
    image: rapiz1/rathole:latest
    restart: always
{% if rathole_mode == "server" %}
    ports:
      - 0.0.0.0:2333:2333
      - 0.0.0.0:2222:22
      - 0.0.0.0:80:80
      - 0.0.0.0:443:443
{% endif %}
    volumes:
      - "./config.toml:/app/config.toml"
    command: "--{{rathole_mode}} /app/config.toml"
    extra_hosts:
      - "host.docker.internal:host-gateway"