api:
  dashboard: true
  debug: true
entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443"
serversTransport:
  insecureSkipVerify: true
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: /config.yml
    watch: true
certificatesResolvers:
  letsencrypt:
    acme:
      email: courgettesmaster@courgettes.club
      storage: acme-letsencrypt.json
      httpchallenge:
        entrypoint: http
  infomaniak:
    acme:
      email: courgettesmaster@courgettes.club
      storage: acme.json
      dnsChallenge:
        provider: infomaniak
        # uncomment this if you have issues pulling certificates through infomaniak, By setting this flag to true disables the need to wait for the propagation of the TXT record to all authoritative name servers.
        disablePropagationCheck: true
        # uncomment along with disablePropagationCheck if needed to ensure the TXT record is ready before verification is attempted
        delayBeforeCheck: 60
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"