[pvenodes]
# not recommended to rename a node that has workloads running. might change that later if backups are working.
host_main_node ansible_host=10.10.0.100 proxmox_node_name=proxmox  has_gpu=yes
host_node_2    ansible_host=10.10.0.101 proxmox_node_name=proxmox2 has_gpu=no
host_node_3    ansible_host=10.10.0.103 proxmox_node_name=proxmox3 has_gpu=no
host_node_4    ansible_host=10.10.0.102 proxmox_node_name=proxmox4 has_gpu=no

[pvenodes:vars]
ansible_user=ansible

[minix]
host_minix ansible_host=10.10.0.201 ansible_user=ymaktepi

[infomaniak]
# assumes that the host exists in .ssh/config
# uses 1password ssh agent
infomaniak_vps

[debian:children]
pvenodes
minix
infomaniak