version: '3.1'
services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    restart: always
    ports:
      - 127.0.0.1:8123:8123
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro