# Temporary: delete after the apply that imports these.
import {
  to = unifi_client.this["netgear_switch"]
  id = "54:07:7d:1d:fa:d1"
}
import {
  to = unifi_client.this["nico_pi"]
  id = "2c:cf:67:30:48:c5"
}
import {
  to = unifi_client.this["proxmox1"]
  id = "74:56:3c:e6:6c:bd"
}
import {
  to = unifi_client.this["proxmox2"]
  id = "98:fa:9b:82:61:fb"
}
import {
  to = unifi_client.this["proxmox3"]
  id = "f8:75:a4:9b:85:fa"
}
import {
  to = unifi_client.this["pbs"]
  id = "98:fa:9b:82:6a:43"
}
import {
  to = unifi_client.this["sarah_nas"]
  id = "00:11:32:3d:1f:48"
}
import {
  to = unifi_client.this["minix"]
  id = "a0:1e:0b:14:af:39"
}
import {
  to = unifi_client.this["synology_nic2"]
  id = "90:09:d0:56:92:12"
}
import {
  to = unifi_client.this["synology_nic1"]
  id = "90:09:d0:56:92:11"
}
import {
  to = unifi_client.this["prusa_mini"]
  id = "08:3a:8d:ce:16:db"
}
import {
  to = unifi_client.this["mystrom_main"]
  id = "b4:8a:0a:b5:33:00"
}
import {
  to = unifi_client.this["mystrom_pc"]
  id = "08:3a:8d:94:3e:4c"
}
import {
  to = unifi_client.this["mystrom_server"]
  id = "c8:f0:9e:be:12:10"
}
import {
  to = unifi_setting.this
  id = "default"
}
