- name: Update and upgrade apt packages
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 #One day

- name: Install default packages
  apt:
    name:
      - curl
      - vim
      - htop
      - wget
    state: latest

- name: Install networkcheckers packages
  when: 'ct_type == "networkcheckers"'
  apt:
    name:
      - python3-pip
      - python3.11-venv
      - supervisor
      - nginx
    state: latest

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /opt/fastapi/run
    state: directory
    mode: '0755'

- name: Install gunicorn and fastapi dependencies
  when: 'ct_type == "networkcheckers"'
  ansible.builtin.shell: |
    systemctl enable supervisor
    systemctl start supervisor
    cd /opt/fastapi
    rm -rf venv
    python3 -m venv venv
    source venv/bin/activate
    venv/bin/pip install fastapi requests uvicorn gunicorn
- name: Create fastapi main
  when: 'ct_type == "networkcheckers"'
  copy:
    src: main.py
    dest: '/opt/fastapi/main.py'
    owner: root
    group: root
    mode: 0644
- name: Create gunicorn conf
  when: 'ct_type == "networkcheckers"'
  template:
    src: gunicorn_start
    dest: '/opt/fastapi/gunicorn_start'
    owner: root
    group: root
    mode: 0777
- name: Create supervisor conf
  when: 'ct_type == "networkcheckers"'
  copy:
    src: supervisor-fast-api.conf
    dest: '/etc/supervisor/conf.d/fastapi-app.conf'
    owner: root
    group: root
    mode: 0644
- name: Restart supervisor
  when: 'ct_type == "networkcheckers"'
  ansible.builtin.shell: |
    supervisorctl reread
    supervisorctl update

- name: Create nginx conf
  when: 'ct_type == "networkcheckers"'
  template:
    src: fastapi-nginx.conf
    dest: '/etc/nginx/sites-available/fastapi-nginx.conf'
    owner: root
    group: root
    mode: 0777

- name: Restart nginx
  when: 'ct_type == "networkcheckers"'
  ansible.builtin.shell: |
    rm -rf /etc/nginx/sites-enabled/fastapi-nginx.conf
    ln -s /etc/nginx/sites-available/fastapi-nginx.conf /etc/nginx/sites-enabled/fastapi-nginx.conf
    nginx -t
    systemctl restart nginx
    pkill gunicorn
