#!/bin/bash

NAME=fastapi-app
DIR=/opt/fastapi
WORKERS=3
WORKER_CLASS=uvicorn.workers.UvicornWorker
VENV=$DIR/venv/bin/activate
BIND=unix:$DIR/run/gunicorn.sock
LOG_LEVEL=error

cd $DIR
source $VENV

exec gunicorn main:app \
  --name $NAME \
  --workers $WORKERS \
  --worker-class $WORKER_CLASS \
  --bind=$BIND \
  --log-level=$LOG_LEVEL \
  --env UNREACHABLE_URLS='{{unreachable_urls}}' \
  --env REACHABLE_URLS='{{reachable_urls}}' \
  --log-file=-