- name: Setup qdevice on minix
  hosts: minix
  become: true
  become_method: sudo
  tasks:
    - name: Install qdevice for quorum on minixx
      apt:
        name:
          - corosync-qnetd
        state: latest

    - name: Start service corosync-qnetd, if not started
      ansible.builtin.service:
        name: corosync-qnetd
        state: started
        enabled: yes

- name: Setup qdevice on pvenodes
  hosts: pvenodes
  become: true
  become_method: sudo
  tasks:
  - name: Install qdevice for quorum on all proxmox nodes
    apt:
      name:
        - corosync-qdevice
      state: latest

  # you still need to add the key of one of the proxmox node as authorized key for the root user of the qdevice
  # as well as enabling root passwordless access
  # then you can run the following on the node that has an authorized key
  #  pvecm qdevice setup {{hostvars['host_minix']['ansible_host']}}

