services:
  traefik:
    image: traefik:v3.7
    container_name: traefik
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 50m
        max-file: "5"
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik
    ports:
      - 80:80
      - 443:443
    environment:
      - INFOMANIAK_ACCESS_TOKEN={{infomaniak_api_token}}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/traefik.yml:/traefik.yml:ro
      - ./data/acme.json:/acme.json
      - ./data/acme-letsencrypt.json:/acme-letsencrypt.json
      - ./data/config.yml:/config.yml:ro
    labels:
      - "traefik.enable=true"


# explicit network since authelia/ldap is bound to traefik for simpler use of hostnames
networks:
  traefik:
    name: traefik
    driver: bridge