- name: Install nginx
  apt:
    name:
      - nginx
    state: latest

- name: Check if ssl certs already exist
  stat:
    path:  /etc/nginx/dhparam.pem
  register: ssl_file

- name: Create SSL self signed certificate
  when: not ssl_file.stat.exists
  ansible.builtin.shell: |
    # following tutorial here: https://www.digitalocean.com/community/tutorials/how-to-create-a-self-signed-ssl-certificate-for-nginx-in-ubuntu-20-04-1
    openssl req -x509 -nodes -days 3650 -newkey rsa:2048 -keyout /etc/ssl/private/nginx-selfsigned.key -out /etc/ssl/certs/nginx-selfsigned.crt -subj "/C=CH/ST=Neuch/L=Neuch/O=Courgettes/OU=CourgettesIT/CN={{ansible_host}}/CN={{courgettes_subdomain}}.{{root_domain}}"
    openssl dhparam -out /etc/nginx/dhparam.pem 4096

- name: Create nginx snippet ssl conf
  copy:
    src: self-signed-nginx.conf
    dest: "/etc/nginx/snippets/self-signed.conf"
    owner: root
    group: root
    mode: 0777

- name: Create nginx snippet ssl params conf
  copy:
    src: nginx-ssl-params.conf
    dest: "/etc/nginx/snippets/ssl-params.conf"
    owner: root
    group: root
    mode: 0777

- name: restart nginx
  service: name=nginx state=restarted
