version: '2'
services:
  factorio:
    image: factoriotools/factorio
    ports:
      - "34197:34197/udp"
      - "27015:27015/tcp"
    volumes:
      # for bigger games, go to the mounted HDD space
      - ./data:/factorio
    restart: always