- name: Create nginx conf
  template:
    src: piratefache-nginx.conf
    dest: '/etc/nginx/sites-available/piratefache-nginx.conf'
    owner: root
    group: root
    mode: 0777

- name: Create a symbolic link for nginx conf
  ansible.builtin.file:
    src: '/etc/nginx/sites-available/piratefache-nginx.conf'
    dest: '/etc/nginx/sites-enabled/piratefache-nginx.conf'
    owner: root
    group: root
    state: link

- name: restart nginx
  service: name=nginx state=restarted

